apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: data-post-process-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-post-process-dev
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      # scale up if usage is above
      # 99% of the requested CPU (100m)
      targetAverageUtilization: 75
