kind: Service
apiVersion: v1
metadata:
  name: gatewayserver
spec:
  type: NodePort
  selector:
    app: gatewayserver
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 31000
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
  labels:
    app: gatewayserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          imagePullPolicy: Always
          image: teamyoda/gatewayserver:latest
          ports:
            - containerPort: 3100