kind: Service
apiVersion: v1
metadata:
  name: gatewayserver
spec:
  # type: NodePort
  selector:
    app: gatewayserver
  ports:
    - name: http
    #- protocol: TCP
      port: 3100
      #targetPort: 3100
      #nodePort: 30100
  #type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
  labels:
    app: gatewayserver
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          imagePullPolicy: Always
          image: teamyoda/gatewayserver
          ports:
          - name: http
            containerPort: 3100
            protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi