version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: "
      #                       test:1:1,
      #                       apiGatewayConsumerF:1:1,
      #                       dataRetrievalConsumerF:1:1,
      #                       dataModellingConsumerF:1:1,
      #                       dataAnalysisConsumerF:1:1,
      #                       sessionManagementConsumerF1:1,
      #                       sessionManagementConsumerApiF:1:1,
      #                     "