kind: Service
apiVersion: v1
metadata:
  name: frontend-dev
spec:
  # type: NodePort
  selector:
    app: frontend-dev
  ports:
    - name: http
      port: 3000
      # targetPort: 3000
      # nodePort: 30000
  # type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
  labels:
    app: frontend-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-dev
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
        - name: frontend-dev
          imagePullPolicy: Always
          image: teamyoda/userinterface
          ports:
            - containerPort: 3000