kind: Service
apiVersion: v1
metadata:
  name: user
spec:
  # type: NodePort
  selector:
    app: user
  ports:
    - name: http
    # - protocol: TCP
      port: 3200
  #     targetPort: 3200
  #     nodePort: 30200
  # type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          imagePullPolicy: Always
          image: teamyoda/userapi
          ports:
            - containerPort: 3200